# General
name: Charcha 
description: "An online Audio discussion's platform for any purpose (including programming sessions). "

markdown: redcarpet
highlighter: pygments

paginate: 5
permalink: /:title

# Social share and comments.
disqus-id: yourusername
twitter: yourusername
github: ramaseshan 
google: +yourusername

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"
